### ISSUE TITLE
Help wanted when running the script

### ISSUE THREAD

**Issue by svasim1** [Randy-Hodges/BTD6-Autoplay#1]
I can't seem to get the autoplayV2.py working. I've installed all libraries and tried to change some code, but it won't work! The play_collection_event.py at least gives me the error "Reward symbol not found, exiting program"

**Comment by Randy-Hodges** [comment]
Dude thanks for reaching out. That's hype af. I haven't looked at the code in a while, I look at it later tonight when I finish this take-home exam for college.

**Comment by Randy-Hodges** [comment]
Alright, It seems that there isn't a collection event running right now and that is why the reward symbol is not being found. It just isn't there! The program is essentially working as intended. Your best bet at using the code while a collection event is not running is to find a level that you want to beat (in the expert category on hard mode) and run the autoplayV2.py script by itself. There is an example (currently commented out) in the main function located at the bottom of the autoplayV2.py script. Just import the correct script that you want to run (as in the example) and run the autoplayV2.py script by itself. If you would like to run the same level repeatedly while you sleep (for money farming or some new mechanic they added in the game that I'm not aware of), I would consider either making a new script that clicks through menus with pyautogui and then runs game_loop() from autoplayV2 or I would tweak the play_collection_event script to not look for the event symbol.

**Comment by svasim1** [comment]
Oh okay, thank you for the help! I'll try it out later today!
